# docker-compose.yml
volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount config file
      - prometheus_data:/prometheus # Persistent data volume
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle' # Allows config reload via API
    ports:
      - "9090:9090" # Expose Prometheus UI
    networks:
      - monitor-net
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091" # Expose Pushgateway API
    networks:
      - monitor-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest # Use OSS version
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana # Persistent data volume
    ports:
      - "3000:3000" # Expose Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default Grafana user/pass
      - GF_SECURITY_ADMIN_PASSWORD=admin 
      # - GF_INSTALL_PLUGINS= # Optional: Add plugins if needed
    networks:
      - monitor-net
    depends_on:
      - prometheus # Wait for Prometheus to be available (basic check)
    restart: unless-stopped