# prometheus.yml
global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus runs on port 9090 inside its container

  # Scrape the Pushgateway
  - job_name: 'pushgateway'
    honor_labels: true # Important: Use labels pushed by the job, don't overwrite
    static_configs:
      # Use the service name defined in docker-compose within the docker network
      - targets: ['pushgateway:9091']